"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.userService = exports.orderDetailService = exports.orderService = exports.productTypeService = exports.productService = void 0;
var OrderDetailService_1 = require("./OrderDetailService");
var OrderService_1 = require("./OrderService");
var ProductService_1 = require("./ProductService");
var ProductTypeService_1 = require("./ProductTypeService");
var UserService_1 = require("./UserService");
exports.productService = new ProductService_1.default();
exports.productTypeService = new ProductTypeService_1.default();
exports.orderService = new OrderService_1.default();
exports.orderDetailService = new OrderDetailService_1.default();
exports.userService = new UserService_1.default();
exports.productService.ProductTypeService = exports.productTypeService;
exports.productTypeService.ProductService = exports.productService;
exports.orderService.OrderDetailService = exports.orderDetailService;
exports.orderService.UserService = exports.userService;
exports.orderDetailService.OrderService = exports.orderService;
exports.orderDetailService.ProductService = exports.productService;
exports.userService.OrderService = exports.orderService;
